# Generated by Django 4.0.3 on 2022-04-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('msg', models.CharField(default='', max_length=255)),
                ('timstamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
