# Generated by Django 4.0.3 on 2022-04-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='timstamp',
        ),
    ]
