# Generated by Django 4.0.3 on 2022-04-28 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contacts_email_remove_contacts_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='msg',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='contacts',
            name='timstamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
